import datetime
from typing import Optional

class MarkdownExporter:
  """
  Handles exporting generated travel content to Markdown files.
  """
  def __init__(self, disclaimer: bool = True):
    """
    Initialize the exporter with configuration.

    Args:
       disclaimer (bool): Whether to include a disclaimer in the exported file. Defaults to True.
    """
    self.include_disclaimer = disclaimer

  def export(self, response_text: str, filename: str = "ai_travel_plan.md") -> str:
    """
    Export travel plan to a well-formatted Markdown file.

    Includes metadata such as timestamp and an optional disclaimer.

    Args:
      response_text (str): The agent's output (reasoning and summary) to be saved.
      filename (str, optional): The filename to save as. Defaults to "ai_travel_plan.md".

    Returns:
      str: The absolute or relative path to the saved file.

    Raises:
      IOError: If writing to the file fails.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    metadata = f"""# 🧳 AI Travel Itinerary\n\n**Generated:** {timestamp}\n"""
    disclaimer = "\n> **Disclaimer:** This itinerary is generated by AI and may not reflect real-time prices or availability. Always verify details before booking.\n" if self.include_disclaimer else ""
    content = f"{metadata}{disclaimer}\n---\n\n{response_text}\n"
    with open(filename, "w", encoding="utf-8") as f:
      f.write(content)
    return filename 